#!/bin/bash
echo "List all users on the VM: "
cat /etc/passwd | grep "/home/" | cut -f1 -d:

echo "Select user to delete: "
read user

user_exists=`cat /etc/passwd | grep $user`
if [ -z "$user_exists" ]; then
	echo "User does not exist"
else
	if [ "$(pgrep -u $user)" != "$NULL" ]; then
		sudo kill -9 $(pgrep -u $user)
	fi
	sudo userdel -r $user
	echo "User deleted"
fi

# 2. Write a script which delete an ACTIVE user on the VM.

# First we assume a user called newuser was added to the VM with "sudo adduser newuser"
# Then we assume the user has some processes running.
# Then with this script we terminate the processes and delete the user.
# echo "Listing current users:"
# cat /etc/passwd | grep /home/ | cut -f1 -d:
# echo "Killing all processes currently run by newuser..."
# sudo pkill -u newuser
# echo "Deleting the user newuser"
# sudo userdel newuser
# echo "Listing users after deletion:"
# cat /etc/passwd | grep /home/ | cut -f1 -d:
