#!/bin/bash

echo "======USEFUL COMMANDS======
1-top            show running processes
2-ipconfig -l    list network interfaces
3-pwd            show current folder path
4-uptime         show how long the computer has been running
0-exit"
while :
do
#input
 read -p "Input MENU number [0-4]:" n
#delete all numbers
 n1=`echo $n|sed s'/[0-9]//'g`
#if empty
 if [ -z "$n" ]
 then
 continue
 fi
#if not a number
 if [ -n "$n1" ]
 then
 continue
 fi
#if menu number > 4
 if [ "$n" -gt 4 ]
 then
 continue
 fi
 break
done
case $n in
 1)
 top
 ;;
 2)
 ipconfig -l
 ;;
 3)
 pwd
 ;;
 4)
 uptime
 ;;
 0)
 exit
 ;;
esac
