#!/bin/bash

echo "======USEFUL COMMANDS======
1-top\tshow running processes
2-ipconfig -l\tlist network interfaces
3-pwd\tshow current folder path
4-uptime\tshow how long the computer has been running
5-exit"
while :
do
#input
 read -p "Input MENU number [1-5]:" n
#delete all numbers
 n1=`echo $n|sed s'/[0-9]//'g`
#if empty
 if [ -z "$n" ]
 then
 continue
 fi
#if not a number
 if [ -n "$n1" ]
 then
 continue
 fi
#if menu number > 5
 if [ "$n" -gt 4 ]
 then
 continue
 fi
 break
done
case $n in
 1)
 top
 ;;
 2)
 ipconfig -l
 ;;
 3)
 pwd
 ;;
 4)
 uptime
 ;;
 0)
 break
 ;;
esac
